### ISSUE TITLE
"Feature Request: Simplify Color Selection, Add Default Settings, and Enhance Gestures"

### ISSUE THREAD

**Issue by yankai19900930** [ChasKane/gay-toolbar#2]
Thank you very much to the author for the plugin, which has greatly helped me. I have the following functional requirements that I hope to be supported:

1. **Simplified Color Selection:** I hope the plugin can provide a more streamlined color selection process, as having to manually select colors each time is somewhat cumbersome.

2. **Saving and Loading Default Settings:** I hope the plugin can support saving and loading default settings. With the author's default settings, if one is not careful, all previously set content might be lost, which is a problem for me. Therefore, I would like to be able to save my settings and easily restore them when needed.

3. **Adding Gesture Functions:** Currently, the plugin has two trigger modes: short press and long press. However, when using the long press trigger, I often find myself unconsciously thinking about when to release the button, which can affect the smoothness of the operation. Therefore, I suggest adding other gesture functions, such as "long press and swipe up" to trigger the function. This would make the entire operation process more fluid and reduce unnecessary pauses.

**Comment by ChasKane** [comment]
Thanks for your feedback! It brings me joy to see so many others using my plugin -- I knew the default toolbar would be painful for others like it was for me.

I'm working on 1 and 2 now and as for 3 OMG YES! Swipes were a HUGE part of my inspiration for this toolbar -- if each button could have up to 8 (9 including long-press) secondary actions, then the toolbar could be made MUCH smaller and take up MUCH less space, plus yeah it'd feel much better to use. Like, to indent and de-indent a paragraph, it just makes sense to swipe right and left on a single button respectively. To move it up or down a line, swiping up and down on the same button also makes sense -- that becomes the "paragraph positioning button" if you will, rather than the "indent command" button. That's why in the default settings I have the indent and de-indent commands paired in the same button.

Alas, swipes are not easy to implement, so this will have to come later if at all. If anyone in your group is interested, I'd love to take a crack at it during a paired programming session though.

**Comment by ChasKane** [comment]
@yankai19900930 the color selection has vastly improved in the latest release (1.1.3). I added the option to set all button colors at once, and for new buttons, they randomly select their color from the presets (viewable and editable from the color picker modal) on creation so you can reduce the presets list to just one color if you're creating a bunch of buttons and want a predictable outcome.

I admit that's not ideal, but it's what I've come to in a day's work and I'm very happy with the new experience.

As for saving and loading default settings: I've simplified the defaults and added the set-all-button-colors feature, so it should only take a minute for new users to drastically change the toolbar to their liking I think. I want to have settings saves like you described but it may be a week or more before I can spend another whole day on it like this. Lmk if this is still a crucial feature for you and I'll see what I can do.

Btw you mentioned articles reporting on this plugin -- could you elaborate and/or link to them?

**Comment by yankai19900930** [comment]
Thank the author for your hard work. I'm truly grateful for the convenience you've brought to us mobile phone users. I'll update to the new version and try it out right away.
 
Besides, here's the link to the article you mentioned: https://mp.weixin.qq.com/s/PXXvhyT9UAD_oHiszdw_Og

**Comment by ChasKane** [comment]
🥰🥰🥰 This makes me very happy! And the latest version (1.2.1) includes `Saving and Loading Default Settings` as well as a ton of improvements and bug fixes. Hope you enjoy! Like I said, the button swipes won't be prioritized for a while but you're welcome to fork it and make a PR. lmk if you wanna collaborate on it or need any help.

I'm gonna close this thread since that final feature is noted in the README
