### ISSUE TITLE
Feature Request: CHANGE ICON WITHOUT TOUCHING THE EXISTING COMMAND

### ISSUE THREAD

**Issue by dingdonng22** [ChasKane/gay-toolbar#3]
Hi, I noticed whenever i try to change icon of an existing command, It asks me to set command again then I can modify icons.

But most of the time I only want to change to a new icon with the same command, so I find it a bit complex to change icon.

So when undoubtedly you've created an amazing plugin which helped me disabling the regular toolbar, **is it possible to add a feature where we can modify icons without re-adding the command?**

https://github.com/user-attachments/assets/444bbfb2-b44c-4567-abe7-1e5249381ca2

**Comment by ChasKane** [comment]
Hey love, there are defo aspects of GT that lack the level of polish I'd like, and this is one of them. I've annoyed *myself* already by selecting icons that don't quite remind me what command they indicate, and then realizing I don't have the command string printed anywhere so I have to re-select as you described. Thanks for highlighting this; I'm working on the color picker and settings backups rn; I'll see if I can knock this out this week too. I'm thinking separate the buttons in the button settings so there's one for selecting a command and one for selecting an icon. I'll also print the command string so you can see it immediately without having to tap another button.

**Comment by ChasKane** [comment]
Btw dope keyboard, what app are you using? And what do your buttons do there near the top center -- the mountain, the house, and the package all peek my interest if you're comfortable explaining. I didn't even know lucid had a mountain icon haha. I love the way your brain works ^.^

**Comment by dingdonng22** [comment]
> Btw dope keyboard, what app are you using? And what do your buttons do there near the top center -- the mountain, the house, and the package all peek my interest if you're comfortable explaining. I didn't even know lucid had a mountain icon haha. I love the way your brain works ^.^

Umm, are you talking to me? I don't get it what mountain house you're talking about? But if you mean  you like the way i managed icons,

I use commander to add buttons, and for the GT I can use icons other than lucid from iconize plugin.

**Comment by ChasKane** [comment]
Heck yeah! I love me an unexpected win like this. If you made a "how I use obsidian" walkthrough video and posted it to youtube, the community would probably love it.

Btw you'll probably enjoy upgrading to the latest release. Looks like the icons are misaligned in your video so I infer you're on iphone? I've fixed that bug, and since added a "Saved configs" modal so you can experiment more freely with buttons and layouts.

Your original feature request will require an overhaul of the button settings. I have been neglecting paid work all week so I've really gotta set this down for a while, but if you wanna fork it, the file you're looking for is `chooseNewCommand.ts` and lines 78 and 97 of `GaySettings.tsx`. I'd love to pair code with you on this next week tho tbh.
